# Generated by Django 3.1.6 on 2021-02-08 16:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hizp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('numberinquran', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='juz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('numberinquran', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('السبت', 'السبت'), ('الأحد', 'الأحد'), ('الاثنين', 'الاثنين'), ('الثلاثاء', 'الثلاثاء'), ('الاربعاء', 'الاربعاء'), ('الخميس', 'الخميس'), ('الجمعة', 'الجمعة')], max_length=20)),
                ('hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ruba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('numberinquran', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Achievements', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='surat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('numberinquran', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manger', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_teacher', to='account.manager')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_student', to='account.lecture')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_lecture', to='account.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_teacher', to='account.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence', models.CharField(choices=[('parcode', 'parcode'), ('teacher', 'teacher')], default='parcode', max_length=25)),
                ('manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_settings', to='account.manager')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_teacher', to='account.teacher'),
        ),
        migrations.CreateModel(
            name='aya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberinsurat', models.PositiveIntegerField()),
                ('numberinquran', models.PositiveIntegerField()),
                ('hizp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hizp', to='account.hizp')),
                ('juz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='juz', to='account.juz')),
                ('ruba', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ruba', to='account.ruba')),
                ('surat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='surat', to='account.surat')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(default=datetime.datetime(2021, 2, 8, 18, 55, 20, 222685))),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_absence', to='account.lecture')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_absence', to='account.student')),
            ],
        ),
    ]
