# Generated by Django 3.1.6 on 2021-02-08 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210208_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='manger',
            new_name='manager',
        ),
        migrations.AlterField(
            model_name='absence',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 20, 40, 56, 440665)),
        ),
    ]
