# Generated by Django 3.1.6 on 2021-02-08 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210208_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='barcode',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='barcodeimage',
            field=models.FileField(null=True, upload_to='barcodes'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 23, 18, 1, 84634)),
        ),
    ]
