# Generated by Django 3.1.6 on 2021-02-08 21:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210208_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 23, 37, 22, 557790)),
        ),
        migrations.AlterField(
            model_name='absence',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_absence', to='account.lecture'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_absence', to='account.student'),
        ),
        migrations.AlterField(
            model_name='aya',
            name='hizp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hizp', to='account.hizp'),
        ),
        migrations.AlterField(
            model_name='aya',
            name='juz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juz', to='account.juz'),
        ),
        migrations.AlterField(
            model_name='aya',
            name='ruba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruba', to='account.ruba'),
        ),
        migrations.AlterField(
            model_name='aya',
            name='surat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surat', to='account.surat'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_teacher', to='account.teacher'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='settings',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_settings', to='account.manager'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_teacher', to='account.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student_lecture',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_student', to='account.lecture'),
        ),
        migrations.AlterField(
            model_name='student_lecture',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lecture', to='account.student'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_teacher', to='account.manager'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
