# Generated by Django 3.1.6 on 2021-02-08 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210208_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='barcodeimage',
        ),
        migrations.AlterField(
            model_name='absence',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 23, 58, 40, 802625)),
        ),
    ]
