# Generated by Django 3.1.6 on 2021-02-08 22:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210209_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_aya', to='account.aya'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 0, 53, 11, 797020)),
        ),
    ]
