# Generated by Django 3.1.6 on 2021-02-09 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210209_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='types',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 18, 58, 37, 793623)),
        ),
    ]
