# Generated by Django 3.1.6 on 2021-02-09 21:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20210209_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='student',
        ),
        migrations.AlterField(
            model_name='absence',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 23, 3, 24, 41363)),
        ),
        migrations.AlterField(
            model_name='absence',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_absence', to='account.student_lecture'),
        ),
    ]
