# Generated by Django 3.1.6 on 2021-02-09 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210209_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='absence',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='absence',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 23, 15, 40, 666416)),
        ),
    ]
