# Generated by Django 3.1.6 on 2021-02-10 01:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20210209_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 1, 33, 43, 907375)),
        ),
        migrations.AlterField(
            model_name='aya',
            name='hizp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hizp', to='account.hizp'),
        ),
        migrations.AlterField(
            model_name='aya',
            name='juz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juz', to='account.juz'),
        ),
        migrations.AlterField(
            model_name='aya',
            name='ruba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruba', to='account.ruba'),
        ),
    ]
