# Generated by Django 3.1.6 on 2021-02-10 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210210_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='homework',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 5, 16, 32, 918677)),
        ),
    ]
