# Generated by Django 3.1.6 on 2021-02-11 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20210210_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fathername',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fathernumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 1, 47, 48, 88967)),
        ),
    ]
