# Generated by Django 3.1.6 on 2021-02-12 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20210212_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='paymount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 12, 19, 49, 22, 301146)),
        ),
    ]
